apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-container
          image: python:3.8
          command: ["python", "/mnt/data/app.py"] # Aponta para o caminho correto
          volumeMounts:
            - mountPath: "/mnt/data"
              name: python-storage
      volumes:
        - name: python-storage
          hostPath:
            path: "/mnt/data" # Caminho montado no Minikube
