apiVersion: v1
kind: PersistentVolume
metadata:
  name: python-pv
  namespace: default # Adicione este campo para associar ao namespace correto
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-pvc
  namespace: default # Adicione este campo para associar ao namespace correto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
